Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendDetailsModel.cs
using System;

namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendDetailsModel
    {
        public string BillToName { get; set; }
        
        public string BillToNum { get; set; }

        public string ShipToName { get; set; }

        public string ShipToNum { get; set; }

        public string CustomerClass { get; set; }
        
        public string VendorName { get; set; }
        
        public string ItemCategory { get; set; }

        public string ItemNum { get; set; }

        public DateTime InvoiceDate { get; set; }

        public string Date => InvoiceDate.ToString("MM-dd-yyyy");

        public decimal Quantity { get; set; }
        
        public decimal ExtPrice { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendDrillThroughAllViewModel.cs
namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendDrillThroughAllViewModel
    {
        public bool IsCorporate { get; set; }

        public string DrillThroughDate { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendDrillThroughByTypeViewModel.cs
using ProfitOptics.Modules.Reporting.Enums;

namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendDrillThroughByTypeViewModel
    {
        public bool IsCorporate { get; set; }

        public string DrillThroughDate { get; set; }

        public DailyTrendDrillThroughType DrillThroughType { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendDrillThroughInvoiceViewModel.cs
namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendDrillThroughInvoiceViewModel
    {
        public bool IsCorporate { get; set; }

        public string Date { get; set; }

        public int BillToId { get; set; }

        public string BillToNum { get; set; }

        public string BillToName { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendExportToExcelModel.cs
using ProfitOptics.Framework.Core.Data;

namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendExportToExcelModel : IDataRecord
    {
        [DataField("Sales Rep", "", 1)]
        public virtual string SalesRep { get; set; }

        [DataField("Date", "", 2)]
        public virtual string Date { get; set; }

        [DataField("Customer Name", "", 3)]
        public virtual string BillToName { get; set; }

        [DataField("Customer Number", "", 4)]
        public virtual string BillToNum { get; set; }

        [DataField("Customer Class", "", 5)]
        public virtual string CustomerClass { get; set; }

        [DataField("Vendor", "", 6)]
        public virtual string VendorName { get; set; }

        [DataField("Ship To Name", "", 7)]
        public virtual string ShipToName { get; set; }

        [DataField("Ship To Num", "", 8)]
        public virtual string ShipToNum { get; set; }

        [DataField("Item Category", "", 9)]
        public virtual string ItemCategory { get; set; }

        [DataField("Item Number", "", 10)]
        public virtual string ItemNum { get; set; }

        [DataField("Quantity", "#,##0", 11, true)]
        public virtual decimal Quantity { get; set; }

        [DataField("Revenue", "$#,##0.00", 12, true)]
        public virtual decimal ExtPrice { get; set; }

        [DataField("Shipping Street", "", 13)]
        public virtual string ShippingStreet { get; set; }

        [DataField("Shipping City", "", 14)]
        public virtual string ShippingCity { get; set; }

        [DataField("Shipping State", "", 15)]
        public virtual string ShippingStateProvince { get; set; }

        [DataField("SOP Type", "", 16)]
        public virtual string SOPType { get; set; }

        [DataField("SOP Number", "", 17)]
        public virtual string SOPNumber { get; set; }

        [DataField("Comment 1", "", 18)]
        public virtual string Comment1 { get; set; }

        [DataField("Comment 2", "", 19)]
        public virtual string Comment2 { get; set; }

        [DataField("Comment 3", "", 20)]
        public virtual string Comment3 { get; set; }

        [DataField("Comment 4", "", 21)]
        public virtual string Comment4 { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendGroupedModel.cs
namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendGroupedModel
    {
        public string GroupCode { get; set; }

        public string GroupName { get; set; }

        public decimal Sales { get; set; }

        public decimal GrossProfit { get; set; }

        public decimal GrossMarginPercent { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendInvoiceItemModel.cs
namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendInvoiceItemModel
    {
        public string ItemNumber { get; set; }

        public string ItemDescription { get; set; }

        public decimal UnitPrice { get; set; }

        public decimal UnitCost { get; set; }

        public decimal ExtPrice { get; set; }

        public decimal ExtCost { get; set; }

        public decimal Qty { get; set; }

        public decimal GrossProfitPercent { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendModel.cs
using System;

namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendModel
    {
        public DateTime InvoiceDate { get; set; }

        public string DateString => InvoiceDate.ToString("MM/dd/yyyy");

        public decimal Sales { get; set; }

        public decimal GrossProfit { get; set; }

        public decimal GrossMarginPercent { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DailyTrendViewModel.cs
namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DailyTrendViewModel
    { 
        public bool IsCorporate { get; set; }

        public bool IsSalesRep { get; set; }

        public string StartDateDefault { get; set; }

        public string EndDateDefault { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Models/DailyTrend/DateRangeDto.cs
using System;

namespace ProfitOptics.Modules.Reporting.Models.DailyTrend
{
    public class DateRangeDto
    {
        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }
    }
}

Modules/ProfitOptics.Modules.Reporting/Components/FilterWidgetViewComponent.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProfitOptics.Modules.Reporting.Factories;
using ProfitOptics.Modules.Reporting.Models.ReportFilter;

namespace ProfitOptics.Modules.Reporting.Components
{
    public class FilterWidgetViewComponent : ViewComponent
    {
        private readonly IReportFilterModelFactory _filterModelFactory;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public FilterWidgetViewComponent(IReportFilterModelFactory filterModelFactory, IHttpContextAccessor httpContextAccessor)
        {
            _filterModelFactory = filterModelFactory;
            _httpContextAccessor = httpContextAccessor;
        }

        public IViewComponentResult Invoke()
        {
            int userId = int.Parse(_httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier));

            FilterWidgetViewModel vm = _filterModelFactory.CreateFilterWidgetViewModel(userId);

            return View(vm);
        }
    }
}

Modules/ProfitOptics.Modules.Reporting/Controllers/DailyTrendController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProfitOptics.Framework.Core.Collections;
using ProfitOptics.Framework.Core.Data;
using ProfitOptics.Framework.Web.Framework.Helpers;
using ProfitOptics.Framework.Web.Framework.Helpers.DataTables;
using ProfitOptics.Framework.Web.Framework.Helpers.Extensions;
using ProfitOptics.Framework.Web.Framework.Models;
using ProfitOptics.Modules.Reporting.Enums;
using ProfitOptics.Modules.Reporting.Factories.DailyTrend;
using ProfitOptics.Modules.Reporting.Models.DailyTrend;
using ProfitOptics.Modules.Reporting.Services.DailyTrend;

namespace ProfitOptics.Modules.Reporting.Controllers
{
    [Authorize(Roles = "admin, reporting")]
    public class DailyTrendController : BaseReportingController
    {
        private readonly IDailyTrendModelFactory _dailyTrendModelFactory;
        private readonly IDailyTrendExportService _dailyTrendExportService;

        public DailyTrendController(IDailyTrendModelFactory dailyTrendModelFactory, IDailyTrendExportService dailyTrendExportService)
        {
            _dailyTrendModelFactory = dailyTrendModelFactory;
            _dailyTrendExportService = dailyTrendExportService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            DailyTrendViewModel vm = _dailyTrendModelFactory.CreateDailyTrendViewModel(GetCurrentUserId());

            return View(vm);
        }

        [HttpGet]
        public IActionResult GetDailyTrends([ModelBinder(typeof(DataTablesBinder))]IDataTablesRequest request,
            [FromQuery]DateRangeDto dateRange)
        {
            PagedList<DailyTrendModel> models = _dailyTrendModelFactory.CreateDailyTrendModels(GetCurrentUserId(), dateRange);

            return new LargeJsonResult(models.ToDataTablesResponse(request));
        }

        [HttpGet]
        public IActionResult DrillThroughAll([FromQuery]DateTime drillThroughDate)
        {
            DailyTrendDrillThroughAllViewModel vm = _dailyTrendModelFactory.CreateDailyTrendDrillThroughAllViewModel(GetCurrentUserId(),
                drillThroughDate);

            return View(vm);
        }

        [HttpPost]
        public IActionResult GetInvoicesForDate([ModelBinder(typeof(DataTablesBinder))]IDataTablesRequest request,
            [FromQuery]DateTime drillThroughDate)
        {
            PagedList<DailyTrendDetailsModel> models = _dailyTrendModelFactory.CreateDailyTrendDetailsModels(
                GetCurrentUserId(), request, drillThroughDate);

            return new LargeJsonResult(models.ToDataTablesResponse(request));
        }

        [HttpGet]
        public IActionResult DrillThroughByType(DailyTrendDrillThroughType drillThroughType, DateTime drillThroughDate)
        {
            DailyTrendDrillThroughByTypeViewModel vm = _dailyTrendModelFactory.CreateDailyTrendDrillThroughByTypeViewModel(
                GetCurrentUserId(), drillThroughType, drillThroughDate);

            return View(vm);
        }

        [HttpPost]
        public IActionResult GetInvoicesGroupedByType([ModelBinder(typeof(DataTablesBinder))]IDataTablesRequest request,
            [FromQuery]DailyTrendDrillThroughType drillThroughType, 
            [FromQuery]DateTime drillThroughDate)
        {
            PagedList<DailyTrendGroupedModel> models = _dailyTrendModelFactory.CreateDailyTrendGroupedModels(
                GetCurrentUserId(), request, drillThroughType, drillThroughDate);

            return new LargeJsonResult(models.ToDataTablesResponse(request));
        }

        [HttpGet]
        public IActionResult DrillThroughInvoice(string billToNum, DateTime drillThroughDate)
        {
            DailyTrendDrillThroughInvoiceViewModel vm = _dailyTrendModelFactory.DailyTrendDrillThroughInvoiceViewModel(
                GetCurrentUserId(), billToNum, drillThroughDate);

            return View(vm);
        }

        [HttpPost]
        public IActionResult GetInvoiceItemsForDate([ModelBinder(typeof(DataTablesBinder))]IDataTablesRequest request,
            [FromQuery]int billToId, [FromQuery]DateTime drillThroughDate)
        {
            PagedList<DailyTrendInvoiceItemModel> models = _dailyTrendModelFactory.CreateDailyTrendInvoiceItemModels(
                GetCurrentUserId(), request, billToId, drillThroughDate);

            return new LargeJsonResult(models.ToDataTablesResponse(request));
        }

        [HttpGet]
        public IActionResult ExportDailyTrendsForDateRangeToExcel([FromQuery]DateRangeDto dateRange)
        {
            return ExportDailyTrendsForDateRangeToExcel(dateRange.StartDate, dateRange.EndDate);
        }

        [HttpGet]
        public IActionResult ExportDailyTrendsForDate([FromQuery]DateTime dateTime)
        {
            return ExportDailyTrendsForDateRangeToExcel(dateTime, dateTime);
        }

        [HttpGet]
        public IActionResult ExportDailyTrendsForCurrentMonths()
        {
            DateTime now = DateTime.Now;

            return ExportDailyTrendsForDateRangeToExcel(new DateTime(now.Year, now.Month, 1), now);
        }

        private IActionResult ExportDailyTrendsForDateRangeToExcel(DateTime startDate, DateTime endDate)
        {
            MemoryStream excelFile =
                _dailyTrendExportService.ExportDailyTrendsExcel(GetCurrentUserId(), startDate, endDate);

            return File(excelFile,
                ExcelFile.ExcelContentType,
                $"Daily Trend Report {DateTime.Now:MM-dd-yyyy--hh-mm}.xlsx");
        }
    }
}

Modules/ProfitOptics.Modules.Reporting/Views/DailyTrend/DrillThroughAll.cshtml
@using ProfitOptics.Modules.Reporting
@using ProfitOptics.Modules.Reporting.Models.DailyTrend
@model DailyTrendDrillThroughAllViewModel
@{
    ViewBag.Title = "Daily Trend - Drill Through";
}

<section class="content">
    @await Component.InvokeAsync("FilterWidget")

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        Daily Trend Analysis for @Model.DrillThroughDate
                    </h3>
                </div>
                <div class="box-body">
                    <div class="add-scroll-small-res">
                        <table id="daily-trend-tbl" class="table table-bordered table-hover font-condensed">
                            <thead>
                                <tr>
                                    <th>Customer Number</th>
                                    <th>Customer Name</th>
                                    <th>Ship To Address Code</th>
                                    <th>Ship To Name</th>
                                    <th>Channel</th>
                                    <th>Product Category</th>
                                    <th>Family</th>
                                    <th>Item Number</th>
                                    <th>Date</th>
                                    <th>Quantity</th>
                                    <th>Revenue</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="10" style="text-align:right !important">Total</th>
                                    <th class="footer-total" style="text-align:right !important"></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <div class="overlay table-overlay" hidden><i class="fa fa-refresh fa-spin"></i></div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>

@section styles {
    <style type="text/css">
        .NegativeValueColor {
            color: red;
        }

        .popover {
            max-width: 400px
        }
    </style>
}

@section scripts {
    <script type="text/javascript">
        var formatStringPositive = "<span class='datacell'>{0}</span>";
        var formatStringNegative = "<span class='datacell NegativeValueColor'>{0}</span>";
        var isAdmin = @(Model.IsCorporate ? "true" : "false");

        // List all menus that should be activated when this page is opened
        app.activeMenus = ["menuReporting", "menuDailyTrend"];

        // Encapsulate page logic. Check out page.js for example of public and private methods and properties
        (function(page, $, undefined) {
            page.onApplyFilterClicked = function() {
                page.reloadTablesAndCharts();
            }

            page.reloadTablesAndCharts = function() {
                $("#daily-trend-tbl").DataTable().ajax.reload();
            }
        }(window.page = window.page || {}, jQuery));

        var dataTableColumns = [
            {
                data: "BillToNum",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.BillToNum;
                }
            },
            {
                data: "BillToName",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.BillToName;
                }
            },
            {
                data: "ShipToNum",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.ShipToNum;
                }
            },
            {
                data: "ShipToName",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.ShipToName;
                }
            },
            {
                data: "CustomerClass",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.CustomerClass;
                }
            },
            {
                data: "VendorName",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.VendorName;
                }
            },
            {
                data: "ItemCategory",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.ItemCategory;
                }
            },
            {
                data: "ItemNum",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.ItemNum;
                }
            },
            {
                data: "Date",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.Date;
                }
            },
            {
                data: "Quantity",
                orderable: false,
                className: "text-right",
                render: function (data, type, full, meta) {
                    return full.Quantity;
                }
            },
            {
                data: "ExtPrice",
                orderable: false,
                className: "text-right",
                render: function (data, type, full, meta) {
                    return helpers.formatMoney(full.ExtPrice, 2, 0.00, formatStringPositive, formatStringNegative);
                }
            }];


        $(document).ready(function() {
            var dataTable = $('#daily-trend-tbl').on('preXhr.dt',
                function(e, settings, data) {
                    $('#daily-trend-tbl').parents(".row").find(".table-overlay").show();
                }).on('xhr.dt',
                function(e, settings, json, xhr) {
                    $('#daily-trend-tbl').parents(".row").find(".table-overlay").hide();
                }).DataTable({
                lengthChange: true,
                autoWidth: false,
                processing: true,
                serverSide: true,
                searching: false,
                ordering: true,
                paging: true,
                info: true,
                pageLength: 100,
                lengthMenu: [10, 25, 50, 100, 250, 500],
                ajax: {
                    url: '@Url.Action("GetInvoicesForDate", "DailyTrend", new { area = ReportingSettings.AreaName, drillThroughDate = Model.DrillThroughDate })',
                    type: "POST"
                },
                footerCallback: function ( row, data, start, end, display ) {
                    var pageTotal = 0;

                    $.each(data, function(i, val) {
                        pageTotal += val.ExtPrice;
                    });

                    $(".footer-total").html(helpers.formatMoney(pageTotal, 0, 0.00, formatStringPositive, formatStringNegative));
                },
                language: {
                    processing: ''
                },
                columns: dataTableColumns
            });
        });
    </script>
}

Modules/ProfitOptics.Modules.Reporting/Views/DailyTrend/DrillThroughByType.cshtml
@using ProfitOptics.Modules.Reporting
@using ProfitOptics.Modules.Reporting.Models.DailyTrend
@using ProfitOptics.Modules.Reporting.Enums
@model DailyTrendDrillThroughByTypeViewModel
@{
    ViewBag.Title = "Daily Trend - Drill Through";
}

<section class="content">
    @await Component.InvokeAsync("FilterWidget")

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        Daily Trend Analysis for @Model.DrillThroughDate
                    </h3>
                </div>
                <div class="box-body">
                    <div class="add-scroll-small-res">
                        <table id="daily-trend-tbl" class="table table-bordered table-hover font-condensed">
                            <thead>
                                <tr>
                                    @{
                                        switch (Model.DrillThroughType)
                                        {
                                            case DailyTrendDrillThroughType.BillTo:
                                                {
                                                    <th>BillTo Number</th>
                                                    <th>BillTo Name</th>
                                                    break;
                                                }
                                            case DailyTrendDrillThroughType.ShipTo:
                                                {
                                                    <th>ShipTo Number</th>
                                                    <th>ShipTo Name</th>
                                                    break;
                                                }
                                            case DailyTrendDrillThroughType.SalesRep:
                                                {
                                                    <th>SalesRep Name</th>
                                                    break;
                                                }
                                            case DailyTrendDrillThroughType.CustomerClass:
                                                {
                                                    <th>Customer Class</th>
                                                    break;
                                                }
                                            case DailyTrendDrillThroughType.ItemCategory:
                                                {
                                                    <th>Item Category</th>
                                                    break;
                                                }
                                        }
                                    }
                                    <th>Sales $</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="@(Model.DrillThroughType == DailyTrendDrillThroughType.BillTo || Model.DrillThroughType == DailyTrendDrillThroughType.ShipTo ? 2 : 1)" style="text-align:right !important">Total</th>
                                    <th class="footer-total" style="text-align:right !important"></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <div class="overlay table-overlay" hidden><i class="fa fa-refresh fa-spin"></i></div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>

@section styles {
    <style type="text/css">
        .NegativeValueColor {
            color: red;
        }

        .popover {
            max-width: 400px
        }
    </style>
}

@section scripts {
    <script type="text/javascript">
        var formatStringPositive = "<span class='datacell'>{0}</span>";
        var formatStringNegative = "<span class='datacell NegativeValueColor'>{0}</span>";
        var isAdmin = @(Model.IsCorporate ? "true" : "false");

        // List all menus that should be activated when this page is opened
        app.activeMenus = ["menuReporting", "menuDailyTrend"];

        // Encapsulate page logic. Check out page.js for example of public and private methods and properties
        (function(page, $, undefined) {
            page.onApplyFilterClicked = function() {
                page.reloadTablesAndCharts();
            }

            page.reloadTablesAndCharts = function() {
                $("#daily-trend-tbl").DataTable().ajax.reload();
            }
        }(window.page = window.page || {}, jQuery));
        
        var dataTableColumns = [
            {
                data: "GroupCode",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    var drillThroughType = @((int)Model.DrillThroughType);
                    var billToTypeValue = @((int)DailyTrendDrillThroughType.BillTo);

                    if (drillThroughType === billToTypeValue) {
                        return '<a href="@Html.Raw(Url.Action("DrillThroughInvoice", "DailyTrend"))?billToNum='
                            + full.GroupCode + '&drillThroughDate=@Model.DrillThroughDate">' + full.GroupCode + '</a>';
                    } else {
                        return full.GroupCode;
                    }
                }
            },
            {
                data: "Name",
                orderable: false,
                className: "text-left",
                render: function (data, type, full, meta) {
                    return full.GroupName;
                }
            },
            {
                data: "Sales",
                orderable: false,
                className: "text-right",
                render: function (data, type, full, meta) {
                    return helpers.formatMoney(full.Sales, 2, 0.00, formatStringPositive, formatStringNegative);
                }
            }];

        function getDrillThroughColumns() {
            var columns = [];

            switch (@((int)Model.DrillThroughType)) {
                case @((int)DailyTrendDrillThroughType.BillTo):
                    columns = getBillToDrillThroughColumns();
                    break;
                case @((int)DailyTrendDrillThroughType.ShipTo):
                    columns = getShipToDrillThroughColumns();
                    break;
                case @((int)DailyTrendDrillThroughType.SalesRep):
                    columns = getSalesRepDrillThroughColumns();
                    break;
                case @((int)DailyTrendDrillThroughType.CustomerClass):
                    columns = getCustomerClassDrillThroughColumns();
                    break;
                case @((int)DailyTrendDrillThroughType.ItemCategory):
                    columns = getItemCategoryDrillThroughColumns();
            }

            return columns;
        }

        function getBillToDrillThroughColumns() {
            return dataTableColumns;
        }

        function getShipToDrillThroughColumns() {
            return dataTableColumns;
        }

        function getSalesRepDrillThroughColumns() {
            var columns = dataTableColumns.filter(function (column) {
                return column.data !== "GroupCode";
            });

            return columns;
        }

        function getCustomerClassDrillThroughColumns() {
            var columns = dataTableColumns.filter(function (column) {
                return column.data !== "GroupCode";
            });

            return columns;
        }

        function getItemCategoryDrillThroughColumns() {
            var columns = dataTableColumns.filter(function (column) {
                return column.data !== "GroupCode";
            });

            return columns;
        }

        $(document).ready(function() {
            var dataTable = $('#daily-trend-tbl').on('preXhr.dt',
                function(e, settings, data) {
                    $('#daily-trend-tbl').parents(".row").find(".table-overlay").show();
                }).on('xhr.dt',
                function(e, settings, json, xhr) {
                    $('#daily-trend-tbl').parents(".row").find(".table-overlay").hide();
                }).DataTable({
                lengthChange: true,
                autoWidth: false,
                processing: true,
                serverSide: true,
                searching: false,
                ordering: true,
                paging: true,
                info: true,
                pageLength: 100,
                lengthMenu: [10, 25, 50, 100, 250, 500],
                ajax: {
                    url:
                        '@Html.Raw(Url.Action("GetInvoicesGroupedByType", "DailyTrend", new { area = ReportingSettings.AreaName, drillThroughType = Model.DrillThroughType, drillThroughDate = Model.DrillThroughDate }))',
                    type: "POST"
                },
                footerCallback: function ( row, data, start, end, display ) {
                    var pageTotal = 0;

                    $.each(data, function(i, val) {
                        pageTotal += val.Sales;
                    });
                    
                    $(".footer-total").html(helpers.formatMoney(pageTotal, 0, 0.00, formatStringPositive, formatStringNegative));
                },
                language: {
                    processing: ''
                },
                columns: getDrillThroughColumns()
            });
        });
    </script>
}